//vector ---->

#include <iostream>
#include <vector>
using namespace std;

int main (){
//-----------------------------------------------------------------------------------
    // vector <int> v;
    // v.push_back(1);
    // v.push_back(2);
    // cout << v[0]<< " "<< v[1]<< endl;     
//------------------------------------------------------------------------------------

    // vector <int> v;
    // v.push_back(1);
    // v.push_back(2);
    // v.push_back(3);
    // v.push_back(4);
    // v.push_back(5);
    // cout << v[0]<< " "<< v[1]<< " "<< v[2]<< " "<< v[3]<< " "<< v[4]<< endl;

    // for (vector < int> :: iterator it = v.begin(); it != v.end(); it++) {
    // cout << *it <<" " << endl;
    // }
//-------------------------------------------------------------------------------------


    return 0;
    //end{code}
}